defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "extension"
    values:
      extension: true
  - scope:
      path: "node"
    values:
      node: true
  - scope:
      path: "blog"
    values:
      blog: true
  - scope:
      path: "_posts"
      type: posts
    values:
      blog: true
      is_post: true
      permalink: /blog/:title:output_ext