- hosts: all

  vars:
    log_dir: /var/log/nginx

  tasks:
  - name: "List nginx logs"
    shell: (cd {{log_dir}}; find . -maxdepth 1 -type f) | cut -d'/' -f2
    register: files_to_copy

  - name: "Fetch nginx logs"
    fetch:
      src: "{{log_dir}}/{{ item }}"
      dest: "../logs/"
      validate_checksum: false
      flat: true
    with_items: "{{ files_to_copy.stdout_lines }}"